server:
  port: 8082

spring:
  application:
    name: service2

eureka:
  instance:
    instance-id: service2-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka