server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
      routes:
        - id: service1
          uri: lb://SERVICE1
          predicates:
           - Path= /service1/**
        - id : service2
          uri: lb://SERVICE2
          predicates:
            - Path=/service2/**
        - id : fastapi-route
          uri : http://127.0.0.1:8000/fastapi1
          predicates:
            - Path= /fastapi1/**
        - id : fastapi-route
          uri : http://127.0.0.1:8000/fastapi2
          predicates:
            - Path=/fastapi2/**

