server:
  port: 8081

spring:
  application:
    name: service1

eureka:
  instance:
    instance-id: service1-instance

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka